Repository openedx/frontend-app-payment, pull requests merged in 2023-03, with the labels that each got.

#718 feat: mrazadar/PON-82/subscription-api-mock-and-design-changes
  .env.development
  .env.development-stage
  .env.test
  .gitignore
  src/data/reducers.js
  src/data/sagas.js
  src/index.scss
  src/payment/PaymentPage.test.jsx
  src/payment/cart/Cart.test.jsx
  src/payment/cart/CartSkeleton.jsx
  src/payment/cart/LocalizedPrice.jsx
  src/payment/cart/OrderSummary.jsx
  src/payment/cart/TotalTable.jsx
  src/payment/checkout/Checkout.jsx
  src/payment/checkout/Checkout.test.jsx
  src/payment/checkout/payment-form/StripePaymentForm.jsx
  src/payment/checkout/payment-form/StripePaymentForm.test.jsx
  src/payment/data/redux.test.js
  src/payment/data/sagas.js
  src/payment/data/sagas.test.js
  src/payment/data/selectors.js
  src/payment/data/service.js
  src/payment/data/utils.js
  src/subscription/SubscriptionPage.jsx
  src/subscription/cart/SubscriptionCart.jsx
  src/subscription/cart/content/SubscriptionContent.jsx
  src/subscription/cart/order-details/SubscriptionOrderDetails.jsx
  src/subscription/checkout/StripeOptions.js
  src/subscription/checkout/SubscriptionCheckout.jsx
  src/subscription/checkout/monthly-billing-notification/MonthlyBillingNotification.jsx
  src/subscription/checkout/skeleton/CheckoutSkeleton.jsx
  src/subscription/checkout/submit-button/SubscriptionSubmitButton.jsx
  src/subscription/confirmation-modal/ConfirmationModal.jsx
  src/subscription/data/client-secret/actions.js
  src/subscription/data/client-secret/reducer.js
  src/subscription/data/client-secret/sagas.js
  src/subscription/data/client-secret/selectors.js
  src/subscription/data/constants.js
  src/subscription/data/details/actions.js
  src/subscription/data/details/reducer.js
  src/subscription/data/details/sagas.js
  src/subscription/data/details/selectors.js
  src/subscription/data/index.js
  src/subscription/data/reducers.js
  src/subscription/data/sagas.js
  src/subscription/data/service.js
  src/subscription/details/SubscriptionDetails.jsx
  src/subscription/details/content/SubscriptionContent.jsx
  src/subscription/details/legal/SubscriptionLegal.jsx
  src/subscription/details/legal/messages.js
  src/subscription/details/order-details/SubscriptionOrderDetails.jsx
  src/subscription/details/skeleton/SubscriptionDetailsSkeleton.jsx
  src/subscription/index.jsx
  src/subscription/index.scss
  src/subscription/subscription-methods/index.js
  src/subscription/subscription-methods/stripe/service.js
Labels: engineering review

#721 Update order detail message [REV-3440]
  src/i18n/messages/ar.json
  src/i18n/messages/de.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fr.json
  src/i18n/messages/fr_CA.json
  src/i18n/messages/hi.json
  src/i18n/messages/it.json
  src/i18n/messages/pt.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
  src/payment/cart/order-details/__snapshots__/OrderDetails.test.jsx.snap
  src/payment/cart/order-details/messages.js
Labels: architecture review

#709 chore(i18n): add more languages
  Makefile
  src/i18n/index.jsx
  src/i18n/messages/de_DE.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt_PT.json
Labels: open-source-contribution
